/* global React */

// ============================================================
// Pricing data — single source of truth
// ============================================================
const GROWTH_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    blurb: 'For media buyers stepping into automated campaign ops.',
    monthly: 349,
    annual: 291,
    cta: 'Start free trial',
    ctaKind: 'primary',
    trial: { dot: true, title: '14 day free trial', meta: 'No credit card required' },
    trailing: 'Then $349/month. Cancel any time before day 14.',
    creditPill: '[TBD] Genie credits per month',
    creditPillStyle: 'filled',
    sections: [
      { name: 'Account', items: ['Unlimited team members', 'Up to 5 ad accounts'] },
      { name: 'Campaign ops', items: ['Bulk Launcher (manual)', 'Basic Automation rules'] },
      { name: 'Platforms', items: ['Meta', 'TikTok', 'NewsBreak'] },
      { name: 'AI', items: ['AI Co-pilot (always on)'] },
      { name: 'Reporting', items: ['Multi Ad Account Reporting', 'RedTrack + Voluum'] },
      { name: 'Support', items: ['Email support'] },
    ],
    footer: 'Genie credits billed on top of plan access. Top up any time.',
  },
  {
    id: 'pro',
    name: 'Pro',
    blurb: 'For performance teams scaling across platforms with full automation.',
    monthly: 599,
    annual: 499,
    cta: 'Start free trial',
    ctaKind: 'primary',
    popular: true,
    trial: { dot: true, title: '14 day free trial', meta: 'No credit card required' },
    trailing: 'Then $599/month. Cancel any time before day 14.',
    creditPill: '[TBD] Genie credits per month',
    creditPillStyle: 'filled',
    sections: [
      { name: 'Account', items: ['Unlimited team members', 'Up to 15 ad accounts'] },
      { name: 'Campaign ops', items: ['Bulk Launcher (automated)', 'Advanced Automation rules', 'Campaign Cloning'] },
      { name: 'Platforms', items: ['Meta · TikTok · NewsBreak'] },
      { name: 'AI', items: ['AI Co-pilot (always on)'] },
      { name: 'Reporting', items: ['Multi Ad Account Reporting', 'Cross platform reporting', 'RedTrack + Voluum'] },
      { name: 'Support', items: ['Priority support'] },
    ],
    footer: 'Built for teams running real budgets across multiple platforms.',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    blurb: 'For agencies and high volume operators with complex stacks.',
    monthly: null, annual: null,
    customLabel: 'Custom',
    customSub: 'tailored to your scale',
    cta: 'Book a call',
    ctaKind: 'outline',
    trial: { dot: true, title: 'Tailored trial', meta: 'Talk to sales' },
    trailing: "We'll set up a tailored trial based on your scale.",
    creditPill: 'Custom credit allocation',
    creditPillStyle: 'outline',
    sections: [
      { name: 'Account', items: ['Unlimited team members', 'Unlimited ad accounts'] },
      { name: 'Campaign ops', items: ['Everything in Pro'] },
      { name: 'Integrations', items: ['API access'] },
      { name: 'Reporting', items: ['Multi Ad Account Reporting', 'Cross platform reporting', 'RedTrack + Voluum', 'Custom dashboards'] },
      { name: 'Support', items: ['Dedicated CSM', 'White glove onboarding', 'SLA backed support'] },
    ],
    footer: 'Pricing tailored to your volume, accounts, and integration needs.',
  },
];

const AI_PLANS = [
  {
    id: 'ai-creator',
    name: 'Creator',
    blurb: 'Solo affiliates and creators generating ad creative on demand.',
    monthly: 49, annual: 41,
    cta: 'Start free trial',
    ctaKind: 'primary',
    trial: { dot: true, title: '7 day free trial', meta: 'No credit card required' },
    trailing: 'Then $49/month. Cancel anytime.',
    creditPill: '500 Genie credits per month',
    creditPillStyle: 'filled',
    sections: [
      { name: 'Generation', items: ['500 creative generations / mo', 'Static + carousel formats'] },
      { name: 'Library', items: ['Personal creative library', 'Export to PNG / MP4'] },
      { name: 'AI', items: ['AI Co-pilot (basic)'] },
      { name: 'Support', items: ['Email support'] },
    ],
    footer: 'For solo operators who need creative fast.',
  },
  {
    id: 'ai-studio',
    name: 'Studio',
    blurb: 'In-house creative teams shipping at brand-team scale.',
    monthly: 199, annual: 166,
    popular: true,
    cta: 'Start free trial',
    ctaKind: 'primary',
    trial: { dot: true, title: '14 day free trial', meta: 'No credit card required' },
    trailing: 'Then $199/month. Cancel anytime.',
    creditPill: '5,000 Genie credits per month',
    creditPillStyle: 'filled',
    sections: [
      { name: 'Generation', items: ['5,000 creative generations / mo', 'Static, carousel, video formats', 'Brand kit + style locks'] },
      { name: 'Library', items: ['Team library', 'Performance tagging', 'Export bundles'] },
      { name: 'AI', items: ['AI Co-pilot (always on)', 'Video Analysis'] },
      { name: 'Support', items: ['Priority support'] },
    ],
    footer: 'Built for in-house creative teams.',
  },
  {
    id: 'ai-scale',
    name: 'Scale',
    blurb: 'Agencies running creative for many brands at once.',
    monthly: null, annual: null,
    customLabel: 'Custom',
    customSub: 'tailored to your output',
    cta: 'Book a call',
    ctaKind: 'outline',
    trial: { dot: true, title: 'Tailored trial', meta: 'Talk to sales' },
    trailing: "We'll set up a tailored trial based on your output.",
    creditPill: 'Custom credit allocation',
    creditPillStyle: 'outline',
    sections: [
      { name: 'Generation', items: ['Unlimited creative generations', 'All formats incl. UGC, Reels'] },
      { name: 'Library', items: ['Multi-brand libraries', 'Performance tagging', 'API access'] },
      { name: 'AI', items: ['Everything in Studio', 'Custom-trained models'] },
      { name: 'Support', items: ['Dedicated CSM', 'SLA backed support'] },
    ],
    footer: 'For agencies operating at high creative volume.',
  },
];

window.PRICING_DATA = { GROWTH_PLANS, AI_PLANS };
